server {
    listen 80;
    server_name akhgam.com www.akhgam.com;

    client_max_body_size 100M;

    location /static/ {
        alias /home/arunsanjeevms/akhgam-herbals/static/;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/arunsanjeevms/akhgam-herbals/akhgam-herbals.sock;
        proxy_read_timeout 120s;
    }
}

server {
    listen 80 default_server;
    listen 443 ssl default_server;
    server_name 20.44.48.64 _;

    ssl_certificate /etc/ssl/certs/ssl-cert-snakeoil.pem;
    ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;

    client_max_body_size 100M;

    location /static/ {
        alias /home/arunsanjeevms/akhgam-herbals/static/;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/arunsanjeevms/akhgam-herbals/akhgam-herbals.sock;
        proxy_read_timeout 120s;
    }
}
